
package package1;


public class frmAdmin extends javax.swing.JFrame {
    
    //Object of varoius frames to call the them
    ViewExamDetails frm1 = new ViewExamDetails();
    frmExamDetails exdetails = new frmExamDetails();
    frmChangeWE dateChange = new frmChangeWE();
    frmAddMarks mksfrm = new frmAddMarks();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmAdmin.class.getName());
    
    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExamdetails = new javax.swing.JButton();
        btnChangeDate = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnAddMarks = new javax.swing.JButton();
        btnAddMarks2 = new javax.swing.JButton();
        btnAddMarks3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExamdetails.setBackground(new java.awt.Color(153, 153, 255));
        btnExamdetails.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnExamdetails.setText("Add Exam Details");
        btnExamdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamdetailsActionPerformed(evt);
            }
        });

        btnChangeDate.setBackground(new java.awt.Color(153, 153, 255));
        btnChangeDate.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnChangeDate.setText("Change Date");
        btnChangeDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDateActionPerformed(evt);
            }
        });

        btnAddStudent.setBackground(new java.awt.Color(153, 153, 255));
        btnAddStudent.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnViewDetails.setBackground(new java.awt.Color(153, 153, 255));
        btnViewDetails.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnViewDetails.setText("View Exam Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnAddMarks.setBackground(new java.awt.Color(153, 153, 255));
        btnAddMarks.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnAddMarks.setText("Add Marks");
        btnAddMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarksActionPerformed(evt);
            }
        });

        btnAddMarks2.setBackground(new java.awt.Color(153, 153, 255));
        btnAddMarks2.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnAddMarks2.setText("Calculate and view Grade");
        btnAddMarks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarks2ActionPerformed(evt);
            }
        });

        btnAddMarks3.setBackground(new java.awt.Color(153, 153, 255));
        btnAddMarks3.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnAddMarks3.setText("Add Reattempt Marks");
        btnAddMarks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarks3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(698, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExamdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChangeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddMarks2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddMarks3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAddMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnExamdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnChangeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnAddMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnAddMarks2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAddMarks3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExamdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamdetailsActionPerformed
        //opening Exam detail page
        exdetails.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExamdetailsActionPerformed

    private void btnChangeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDateActionPerformed
       //Opening date change page
        dateChange.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChangeDateActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        //opening view exxam details button
        frm1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        //opening Add stdent page
        frmAddStd std1 =new frmAddStd();
        std1.setVisible(true);
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarksActionPerformed
       //opening add marks page
        mksfrm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnAddMarksActionPerformed

    private void btnAddMarks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarks2ActionPerformed
       //opening view and add grade button
        frmAddGrade addgrade = new frmAddGrade();
        addgrade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddMarks2ActionPerformed

    private void btnAddMarks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarks3ActionPerformed
       //Opening reattempt page
        frmReattemptMarks frm = new frmReattemptMarks();
       frm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnAddMarks3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMarks;
    private javax.swing.JButton btnAddMarks2;
    private javax.swing.JButton btnAddMarks3;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnChangeDate;
    private javax.swing.JButton btnExamdetails;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
